hydra-genetics/snv_indels

- workflow/envs/bcftools.yaml
- workflow/envs/freebayes.yaml
- workflow/rules/bcftools.smk
- workflow/rules/common.smk
- workflow/rules/mutect2.smk
> fix: fix gvcf output name

- .github/workflows/integration.yaml
- .github/workflows/snakemake-dry-run.yaml
> ci: update dependencies

- workflow/rules/gatk.smk
> fix: wrong parameter name

- .tests/compatibility/config.yaml
- COMPATIBLITY.md
- README.md
> fix: update compatibility config-file

- workflow/rules/bcbio_variation_recall.smk
> chore: make bcbio tempfiles temp in rule

- workflow/rules/gatk.smk
> feat: update wrapper version

- COMPATIBLITY.md
> docs: update compatibility list

- requirements.txt
- workflow/rules/common.smk
> feat: update snakemake-version

- .github/workflows/integration.yaml
> fix: set strict mode for conda

- workflow/scripts/mutect2_pass_filter.py
> fix: added multiallelic variants to mutect2_pass_filter

- COMPATIBLITY.md
- README.md
- requirements.txt
> docs: update compatibility

- .tests/integration/config.yaml
- config/config.yaml
- workflow/rules/mutect2_pass_filter.smk
- workflow/schemas/config.schema.yaml
- workflow/scripts/mutect2_pass_filter.py
> feat: make mutect2_pass_filter configurable

- .github/workflows/compatibility.yaml
- .github/workflows/integration.yaml
- .github/workflows/lint.yaml
- .github/workflows/pycodestyle.yaml
- .github/workflows/pytest.yaml
- .github/workflows/snakemake-dry-run.yaml
> ci: remove conda from compatibility action

- workflow/scripts/fix_af.py
> fix: fix_af.py

- .github/workflows/integration_deepvariant.yaml
- .github/workflows/snakemake-dry-run_deepvariant.yaml
- .tests/integration/config.yaml
- .tests/integration/config_deepvariant.yaml
- workflow/rules/common.smk
> test: run the deepvariant and deeptrio testing separately

- .tests/integration/config_deepvariant.yaml
> test: Add glnexus container to deepvariant integration config

- workflow/scripts/fix_af.py
> refactor: added pbrun_mutectcaller_T to callers

- .github/workflows/integration_deepvariant.yaml
> ci: fix failing test due to space limitations

- workflow/schemas/config.schema.yaml
- workflow/schemas/resources.schema.yaml
> fix: update schema with correct key value for gatk_mutect2_filter

- workflow/rules/bcftools.smk
- workflow/schemas/rules.schema.yaml
> fix: sort shouldn't require a tbi file

- README.md
> docs: add link to readthedocs

- requirements.txt
- workflow/rules/tabix.smk
> fix(tabix): fix log filename

- requirements.txt
> fix: remove extra pulp in requirements

- requirements.txt
- workflow/Snakefile
- workflow/rules/common.smk
Added ruleorders so they do not need to be declared in the pipeline when importing the rule
> feat: added ruleorders

- workflow/schemas/rules.schema.yaml
> docs: explain the optional gVCF output for deepvariant

- .tests/units/.tests/merge_af.normalized.sorted.missing_VD.vcf
- .tests/units/.tests/merge_af.normalized.sorted.vcf
- .tests/units/merge_af_test.py
- config/config.yaml
- docs/softwares.md
- requirements.txt
- workflow/Snakefile
- workflow/rules/bcbio_variation_recall.smk
- workflow/rules/merge_af_complex_variants.smk
- workflow/schemas/config.schema.yaml
- workflow/schemas/resources.schema.yaml
- workflow/schemas/rules.schema.yaml
- workflow/scripts/merge_af.py
Added: A feature that gives a user the option to select one or sum records for complex variants reported in the vcf-file.
- Only unit testing implemented
> feat: Merge af complex

- .github/workflows/integration.yaml
> test: change apptainer install to work with ubuntu 24.04

- .tests/integration/config_deepsomatic.yaml
- .tests/integration/config_mosaic.yaml
- config/config.yaml
- workflow/rules/deepmosaic.smk
- workflow/rules/deepsomatic.smk
- workflow/schemas/config.schema.yaml
- workflow/schemas/rules.schema.yaml
> fix: make deepsomatic panel of normal postprocess more flexible

- .tests/integration/config_whatshap.yaml
> test: add deepsomatic docker to fix the integration test

- workflow/scripts/fix_af.py
add  deepsomatic to callers in fix_af.py
> fix: update fix_af.py
